"""Generate the VQ2 KV-cache codebook (src/ops/kv_cache/vq2_codebook.inc).

The VQ2 codec quantizes each eight-value word of a Hadamard-rotated, unit-variance D256 row to one
of 2^16 codewords: a magnitude pattern P[p] (p < 512) with seven free sign bits and an implied
eighth sign that makes the number of negative coordinates even. This tool trains the 512 patterns
with Lloyd iterations on i.i.d. standard Gaussian words (the rotated rows of real K/V are
Gaussian to within sampling error), rounds them to INT8 in units of 1/16 and writes them ordered
by squared norm, then value.

usage: python -m tools.kv_codebook.make_vq2_codebook [--out PATH] [--check]
Requires numpy. --check regenerates the table and compares it with PATH instead of writing.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

PATTERNS = 512
SAMPLES = 600_000
ITERATIONS = 60
SEED = 11
SCALE = 16
DEFAULT_OUT = Path("src/ops/kv_cache/vq2_codebook.inc")


def distances(words: np.ndarray, patterns: np.ndarray) -> np.ndarray:
    """D(p) of the codec contract for every (word, pattern), in units of the pattern values."""
    a = np.abs(words)
    d = (a * a).sum(1, keepdims=True) - 2.0 * a @ patterns.T + (patterns * patterns).sum(1)[None, :]
    odd = ((words < 0).sum(1) % 2).astype(bool)
    if odd.any():
        extra = (a[odd][:, None, :] * patterns[None, :, :]).min(-1)
        d[odd] += 4.0 * extra
    return d


def assign(words: np.ndarray, patterns: np.ndarray, chunk: int = 4096) -> np.ndarray:
    out = np.empty(len(words), np.int64)
    for start in range(0, len(words), chunk):
        out[start : start + chunk] = distances(words[start : start + chunk], patterns).argmin(1)
    return out


def seen_magnitudes(words: np.ndarray, patterns: np.ndarray, index: np.ndarray) -> np.ndarray:
    """|word| as represented by its pattern: the parity-flipped coordinate contributes -|x|."""
    a = np.abs(words).copy()
    odd = ((words < 0).sum(1) % 2).astype(bool)
    flip = np.argmin(a * patterns[index], axis=1)
    rows = np.nonzero(odd)[0]
    a[rows, flip[rows]] = -a[rows, flip[rows]]
    return a


def kmeans_pp(points: np.ndarray, count: int, rng: np.random.Generator) -> np.ndarray:
    chosen = [int(rng.integers(len(points)))]
    nearest = ((points - points[chosen[0]]) ** 2).sum(1)
    for _ in range(count - 1):
        pick = int(rng.choice(len(points), p=nearest / nearest.sum()))
        chosen.append(pick)
        nearest = np.minimum(nearest, ((points - points[pick]) ** 2).sum(1))
    return points[chosen].copy()


def train() -> np.ndarray:
    rng = np.random.default_rng(SEED)
    words = rng.standard_normal((SAMPLES, 8))
    patterns = kmeans_pp(np.abs(words[:50_000]), PATTERNS, rng)
    for _ in range(ITERATIONS):
        index = assign(words, patterns)
        sums = np.zeros_like(patterns)
        np.add.at(sums, index, seen_magnitudes(words, patterns, index))
        counts = np.bincount(index, minlength=PATTERNS)
        refill = np.abs(words[rng.integers(SAMPLES, size=PATTERNS)])
        patterns = np.where((counts == 0)[:, None], refill, sums / np.maximum(counts, 1)[:, None])
    table = np.round(patterns * SCALE).astype(np.int64)
    if table.min() < -128 or table.max() > 127:
        raise SystemExit("trained codebook does not fit INT8")
    rows = sorted({tuple(int(v) for v in row) for row in table}, key=lambda r: (sum(v * v for v in r), r))
    if len(rows) != PATTERNS:
        raise SystemExit("rounding merged codebook patterns")
    return np.array(rows, np.int64)


def render(table: np.ndarray) -> str:
    lines = [
        "// Generated by tools/kv_codebook/make_vq2_codebook.py: 512 magnitude patterns x 8 coordinates,",
        "// INT8 in units of 1/16 of a unit-variance coordinate, ordered by squared norm then value.",
    ]
    lines += ["    " + " ".join(f"{int(v)}," for v in row) for row in table]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render(train())
    if args.check:
        same = args.out.read_text().replace("\r\n", "\n") == text
        print("codebook matches" if same else "codebook differs")
        return 0 if same else 1
    args.out.write_text(text, newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
